### ISSUE TITLE
Ponto de melhoria

### ISSUE THREAD

**Issue by jordyalcides** [lipecayres/rpg#1]
Olá Felipe!

Dando uma olhada neste repositório notei que seu projeto tem muitas linhas de código, e seria interessante começar a dividir melhor as responsabilidades pra mais arquivos, deixando o seu código mais organizado.

É muito importante deixar o código organizado, e com uma boa apresentação para outros devs se situarem melhor ao ler.

**Comment by lipecayres** [comment]
Oi Jordy!
Obrigado pelo feedback. Realmente dividindo o código ficaria melhor.
Vou estudar como fazer essa divisão e implementar aqui!!

**Comment by lipecayres** [comment]
Resolvido!

**Comment by lipecayres** [comment]
Resolvido!
